language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-5.3
- export CXX="g++-5.3"

git:
  submodules: false
before_script:
  - cd source
script:
  - make STAR
